//
// Created by daming on 7/24/16.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef EXAMPLE_ANDROID_ALLIVAULT_API_CPP_H
#define EXAMPLE_ANDROID_ALLIVAULT_API_CPP_H

#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jstring JNICALL Java_com_allivault_cloudsafe_playground_AllivaultApi_getMessage(JNIEnv* env,
                                                                        jobject thiz );

JNIEXPORT jstring JNICALL Java_com_allivault_cloudsafe_playground_AllivaultApi_getLibGit2Version
        (JNIEnv *env, jclass cls);

/*
 * Class:     com_allivault_cloudsafe_playground_Apis
 * Method:    aesEncrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_allivault_cloudsafe_playground_AllivaultApi_aesEncrypt
        (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_allivault_cloudsafe_playground_Apis
 * Method:    aesDecrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_allivault_cloudsafe_playground_AllivaultApi_aesDecrypt
        (JNIEnv *, jclass, jbyteArray, jint);

JNIEXPORT jboolean JNICALL Java_com_allivault_cloudsafe_playground_AllivaultApi_createRSAKeyPair
        (JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL
Java_com_allivault_cloudsafe_playground_AllivaultApi_createUserAccountOnServer(JNIEnv *env,
                                                                               jclass type,
                                                                               jstring userName_,
                                                                               jstring passWord_,
                                                                               jstring fullName_,
                                                                               jstring emailAddress_,
                                                                               jstring publicKeyFile_,
                                                                               jlong curTime,
                                                                               jlong expirationTime,
                                                                               jlong quotaSize);

JNIEXPORT void JNICALL
Java_com_allivault_cloudsafe_playground_AllivaultApi_processNewUser(JNIEnv *env, jclass type,
                                                                    jstring userName_);

JNIEXPORT void JNICALL
        Java_com_allivault_cloudsafe_playground_AllivaultApi_batchActionsForNewMachine(JNIEnv *env, jclass type);

JNIEXPORT void JNICALL
        Java_com_allivault_cloudsafe_playground_AllivaultApi_appInitialize(JNIEnv *env, jclass type,
                                                                            jstring rootPath);

JNIEXPORT jboolean JNICALL
        Java_com_allivault_cloudsafe_playground_AllivaultApi_registerAppStatusUpdated(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif //EXAMPLE_ANDROID_ALLIVAULT_API_CPP_H
